### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by jbruwes** [whs/elFinder-driver#9]
Thank you for the s3 driver. It works really good . But I have a little question. Does it support thumbnails?

**Comment by davo3** [comment]
Hi @whs ,

First of all, wanted to thank you a lot for posting s3 driver, it is almost 2 days I was struggling to get the S3 working - and this worked at once. As im not worried that much about bandwidth I would prefer to have the thumbnails as well, and as you had mentioned you had worked on it, I wanted to ask if you might have some ready/incomplete code for that ? 

Thanks again.

**Comment by whs** [comment]
I never wrote a thumbnail generator. The previous conversation I meant that
this driver was written long time ago and I've already forgot the
implementation details of it.

**Comment by davo3** [comment]
ok, thanks for the reply.
